# Generated by Django 4.0.4 on 2022-05-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_files_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
